CREATE TABLE IF NOT EXISTS user (
	user_id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(30) NOT NULL,
	
	CONSTRAINT user_email_unique UNIQUE (email)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;